### ISSUE TITLE
TikTok's webpages takes forever and end up failing the whole task

### ISSUE THREAD

**Issue by CreaZyp154** [ArchiveTeam/urls-grab#13] opened 2022-04-22 11:47 UTC
It happens quite a lot; there's a task with tiktok in it, and it hangs. It's the one that blocks everything I've checked. It happened with different subdomains as well like `vt.` and `vm.`. 
TikTok is not blocked for me. It works perfectly when opening in the browser.

### Screenshot
![image](https://user-images.githubusercontent.com/73843822/164704238-12d643f6-e623-4a2c-a981-7d8fbeb6f635.png)

### Details
Running on VirtualBox 6.1
Seesaw version: 0.10.3
Python version: 3.9.9 (main, Dec 21 2021, 10:35:05) [GCC 8.3.0]

### Suggestions for fix
I don't have a full solution but I have some ideas:

* It might be due to an anti-bot script 
* It may also NOT be an anti-bot script so, trying to figure out why it behaves like that
* Add a timeout to each element and re-queue them to the tracker (or abandon idk)
* Create custom code for tiktok's domain

**Comment by CreaZyp154** [comment] 2022-12-01 07:50
I haven't seen this happen again, so it may have been fixed, idk...

**Comment by Arkiver2** [comment] 2022-12-28 16:59
From the image the problematic URL would be `https://www.tiktok.com/@saki_15166/live?_r=1&sec_user_id=MS4wLjABAAAADFRCvXBvgK4_u-gP9zPzOvTwljFpMa3YrXZtPr0OYj9Dn7Lr8lT3nkg0EaAmujk4&share_app_id=1180&share_link_id=a29bab9d-02ca-43c7-87e3-baf57c5e7187&source=h5_t&ugbiz_name=Live&user_id=7064603045267506178`

**Comment by Arkiver2** [comment] 2022-12-28 17:06
I can't reproduce this problem, and with comment https://github.com/ArchiveTeam/urls-grab/issues/13#issuecomment-1333342750, I'm going to close this for now.

**Closed by Arkiver2** 2022-12-28 17:06 UTC
